# ARC evaluation/visualization config

defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

# Data paths
data_paths: ['data/arc1concept-aug-1000']
data_paths_test: []

# Checkpoint to load
load_checkpoint: null  # Set this to your checkpoint path
checkpoint_path: null  # Set this for saving results

# Evaluation settings
global_batch_size: 1  # Use batch size 1 for visualization
split: "test"  # Use test split by default

seed: 0

# Number of training epochs for SAE (if doing SAE training)
num_epochs: 10

max_batches: null  # Set to null to use all batches

